# -*- coding: utf-8 -*-
"""tpae.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTHdFANmO4OmqHkR1R_DOkvcW1fa1Ft9
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv('Gaming_Academic_Performance.csv')
df.head(30)


df = df.rename(columns={
    'student_id': 'ID_Aluno',
    'age': 'Idade',
    'gender': 'Gênero',
    'gaming_hours': 'Horas_de_Jogo',
    'study_hours': 'Horas_de_Estudo',
    'sleep_hours': 'Horas_de_Sono',
    'attendance': 'Frequência',
    'gaming_genre': 'Gênero_de_Jogo',
    'social_activity': 'Atividade_Social',
    'device_usage': 'Uso_de_Dispositivo',
    'reaction_time_ms': 'Tempo_de_Reação_ms',
    'addiction_score': 'Pontuação_de_Vício',
    'stress_level': 'Nível_de_Estresse',
    'grades': 'Notas'
})
df.head()


# Criar faixas de horas de uso
df['faixa_uso'] = pd.cut(
  df['Uso_de_Dispositivo'],
  bins=[0, 2, 4, 6, 9, 12],
  labels=['0-2h', '2-4h', '4-6h', '6-8h', '8h+']
)

# Mapear os níveis de estresse para valores numéricos
stress_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
df['stress_level_numeric'] = df['Nível_de_Estresse'].map(stress_mapping)

# Média do estresse por faixa - adicionando observed=True
dados = df.groupby('faixa_uso', observed=True)['stress_level_numeric'].mean()

plt.figure(figsize=(7,4))
dados.plot(kind='bar', color=['rosybrown', 'palevioletred', 'plum', 'mediumorchid', 'purple'])

plt.title('Horas de uso de dispositivos e nível de estresse')
plt.xlabel('Faixa de horas de uso')
plt.ylabel('Nível médio de estresse')
plt.xticks(rotation=0)

plt.show()




study_hours_bins = [0, 2, 4, 6, 8, np.inf]
study_hours_labels = ['0-2 horas', '2-4 horas', '4-6 horas', '6-8 horas', '8+ horas']

df['study_hours_category'] = pd.cut(df['Horas_de_Estudo'], bins=study_hours_bins, labels=study_hours_labels, right=False)

average_grades_by_study = df.groupby('study_hours_category', observed=False)['Notas'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=average_grades_by_study, x='study_hours_category', y='Notas', marker='o', color='green')
plt.title('Média de Notas por Categoria de Horas de Estudo')
plt.xlabel('Horas de Estudo')
plt.ylabel('Média de Notas')
plt.grid(False) # Removido as linhas de grade
plt.xticks(rotation=0, ha='right')
plt.tight_layout()
plt.show()



gaming_hours_bins = [0, 2, 4, 6, 8, np.inf]
gaming_hours_labels = ['0-2 horas', '2-4 horas', '4-6 horas', '6-8 horas', '8+ horas']

df['gaming_hours_category'] = pd.cut(df['Horas_de_Jogo'], bins=gaming_hours_bins, labels=gaming_hours_labels, right=False)

average_grades_by_gaming = df.groupby('gaming_hours_category', observed=False)['Notas'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=average_grades_by_gaming, x='gaming_hours_category', y='Notas', marker='o', color='red')
plt.title('Média de Notas por Categoria de Horas de Jogo')
plt.xlabel('Horas de Jogo')
plt.ylabel('Média de Notas')
plt.grid(False) # Removido as linhas de grade
plt.xticks(rotation=0, ha='right')
plt.tight_layout()
plt.show()



bins = [4, 5, 6, 7, 8, np.inf]
labels = ['4-5 horas', '5-6 horas', '6-7 horas', '7-8 horas', '8+ horas']

df['Categoria_Sono'] = pd.cut(
    df['Horas_de_Sono'],
    bins=bins,
    labels=labels,
    right=False
)

media_notas = (
    df.groupby('Categoria_Sono', observed=True)['Notas']
    .mean()
    .reset_index()
)

plt.figure(figsize=(8,5))

sns.barplot(
    data=media_notas,
    x='Categoria_Sono',
    y='Notas',
    hue='Categoria_Sono',
    palette='rocket',
    legend=False
)

plt.title('Média de Notas por Categoria de Horas de Sono')
plt.xlabel('Horas de Sono')
plt.ylabel('Média de Notas')
plt.grid(False)

plt.tight_layout()
plt.show()