# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esEyLuDEGcPDqdeDH1lP1cyosAJN3tI_

**A Influência dos Jogos Eletrônicos no Desempenho Acadêmico dos jovens**
"""

#UPLOAD DA BASE DE DADOS

from google.colab import files
uploaded = files.upload()

#IMPORTAÇÃO DA BIBLIOTECA ZIP E EXTRAÇÃO DOS ARQUIVOS COMPACTADOS

import zipfile

with zipfile.ZipFile('archive.zip', 'r') as zip_ref:
    zip_ref.extractall('dados')

#VERIFICAÇÃO DOS ARQUIVOS EXTRAÍDOS NA PASTA

import os
print(os.listdir('dados'))

#IMPORTAÇÃO DA BIBLIOTECA PANDAS

import pandas as pd
df = pd.read_csv('dados/Gaming_Academic_Performance.csv')
df.head()

#VERIFICAÇÃO DAS COLUNAS

print(df.columns)

#TRADUÇÃO DAS COLUNAS

df = df.rename(columns={
    'student_id': 'ID_Aluno',
    'age': 'Idade',
    'gender': 'Gênero',
    'gaming_hours': 'Horas_de_Jogo',
    'study_hours': 'Horas_de_Estudo',
    'sleep_hours': 'Horas_de_Sono',
    'attendance': 'Frequência',
    'gaming_genre': 'Gênero_de_Jogo',
    'social_activity': 'Atividade_Social',
    'device_usage': 'Uso_de_Dispositivo',
    'reaction_time_ms': 'Tempo_de_Reação_ms',
    'addiction_score': 'Pontuação_de_Vício',
    'stress_level': 'Nível_de_Estresse',
    'grades': 'Notas'
})
df.head()

#NOVA TABELA COM OS DADOS SELECIONADOS

selected_df = df[['ID_Aluno', 'Notas', 'Horas_de_Jogo']]
selected_df.head(10)

#SELECIONE AS 5 MENORES NOTAS

selected_df.nsmallest(5,'Notas')

#SELECIONE AS TRÊS MAIORES NOTAS

gap_top3 = selected_df.nlargest(3,'Notas')
gap_top3

#NÍVEIS DE ESTRESSE

print(df["Nível_de_Estresse"].unique())

#VERIFICAÇÃO DO NÍVEL DE ESTRESSE BAIXO

df_estresse_baixo =  df[df.stress_level == 'Low']
df_estresse_baixo.head(10)

#VERIFICAÇÃO DO NÍVEL DE ESTRESSE MÉDIO
df_estresse_medio = df[df['Nível_de_Estresse'] == 'Medium']
df_estresse_medio.head(10)

#VERIFICAÇÃO DO NÍVEL DE ESTRESSE ALTO

df_estresse_alto = df[df['Nível_de_Estresse'] == 'High']
df_estresse_alto.head(10)

selected_df = df[df.Idade < 18][['ID_Aluno', 'Idade', 'Notas', 'Horas_de_Jogo', 'Nível_de_Estresse']]
selected_df.head(10)

media_genero = df.groupby('Gênero')['Notas'].mean().reset_index()
display(media_genero)

jogo_genero = df.groupby('Gênero')['Horas_de_Jogo'].mean().reset_index()
display(jogo_genero)

estresse_jogo = df.groupby('Gênero_de_Jogo', observed=True)['stress_level_numeric'].mean().reset_index()
display(estresse_jogo)

notas_genero_jogo = df.groupby('Gênero_de_Jogo')['Notas'].mean().reset_index()
display(notas_genero_jogo)

# TABELA - MÉDIA DE NOTAS POR CATEGORIA DE HORAS DE SONO

tabela_sono = (
    df.groupby('Categoria_Sono', observed=True)['Notas']
    .mean()
    .reset_index()
)

tabela_sono.columns = ['Categoria de Horas de Sono', 'Média de Notas']

display(tabela_sono)

correlacao = df[['Horas_de_Jogo',
                 'Horas_de_Estudo',
                 'Horas_de_Sono',
                 'stress_level_numeric',
                 'Notas']].corr()

display(correlacao)

# TABELA - MÉDIA DE NOTAS POR CATEGORIA DE HORAS DE JOGO

tabela_jogo = (
    df.groupby('gaming_hours_category', observed=True)['Notas']
    .mean()
    .reset_index()
)

tabela_jogo.columns = ['Categoria de Horas de Jogo', 'Média de Notas']

display(tabela_jogo)

import pandas as pd

# TABELA - MÉDIA DE NOTAS POR CATEGORIA DE HORAS DE ESTUDO

tabela_estudo = (
    df.groupby('study_hours_category', observed=True)['Notas']
    .mean()
    .reset_index()
)

tabela_estudo.columns = ['Categoria de Horas de Estudo', 'Média de Notas']

display(tabela_estudo)

import pandas as pd

# TABELA - MÉDIA DO NÍVEL DE ESTRESSE POR CATEGORIA DE USO DE DISPOSITIVOS

tabela_dispositivo = (
    df.groupby('Uso_de_Dispositivo', observed=True)['stress_level_numeric']
    .mean()
    .reset_index()
)

tabela_dispositivo.columns = ['Categoria de Uso de Dispositivos', 'Nível Médio de Estresse']

display(tabela_dispositivo)

print(df['stress_level_numeric'].unique())

# GRÁFICO 1 - MÉDIA DE NOTAS POR CATEGORIA DE HORAS DE SONO

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# CRIAÇÃO DAS CATEGORIAS DE HORAS DE SONO
bins = [4, 5, 6, 7, 8, np.inf]
labels = ['4-5 horas', '5-6 horas', '6-7 horas', '7-8 horas', '8+ horas']

df['Categoria_Sono'] = pd.cut(
    df['Horas_de_Sono'],
    bins=bins,
    labels=labels,
    right=False
)

# CÁLCULO DA MÉDIA DE NOTAS POR CATEGORIA DE SONO
media_notas = (
    df.groupby('Categoria_Sono', observed=True)['Notas']
    .mean()
    .reset_index()
)

# CRIAÇÃO DO GRÁFICO
plt.figure(figsize=(8,5))

sns.barplot(
    data=media_notas,
    x='Categoria_Sono',
    y='Notas',
    hue='Categoria_Sono',
    palette='rocket',
    legend=False
)

# PERSONALIZAÇÃO DO GRÁFICO
plt.title('Média de Notas por Categoria de Horas de Sono')
plt.xlabel('Horas de Sono')
plt.ylabel('Média de Notas')
plt.grid(False)

# AJUSTE FINAL
plt.tight_layout()
plt.show()

#GRÁFICO 2

import pandas as pd
import numpy as np

gaming_hours_bins = [0, 2, 4, 6, 8, np.inf]
gaming_hours_labels = ['0-2 horas', '2-4 horas', '4-6 horas', '6-8 horas', '8+ horas']

df['gaming_hours_category'] = pd.cut(df['Horas_de_Jogo'], bins=gaming_hours_bins, labels=gaming_hours_labels, right=False)

average_grades_by_gaming = df.groupby('gaming_hours_category', observed=False)['Notas'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=average_grades_by_gaming, x='gaming_hours_category', y='Notas', marker='o', color='red')
plt.title('Média de Notas por Categoria de Horas de Jogo')
plt.xlabel('Horas de Jogo')
plt.ylabel('Média de Notas')
plt.grid(False) # Removido as linhas de grade
plt.xticks(rotation=0, ha='right')
plt.tight_layout()
plt.show()

#GRÁFICO 3

import pandas as pd
import numpy as np

study_hours_bins = [0, 2, 4, 6, 8, np.inf]
study_hours_labels = ['0-2 horas', '2-4 horas', '4-6 horas', '6-8 horas', '8+ horas']

df['study_hours_category'] = pd.cut(df['Horas_de_Estudo'], bins=study_hours_bins, labels=study_hours_labels, right=False)

average_grades_by_study = df.groupby('study_hours_category', observed=False)['Notas'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=average_grades_by_study, x='study_hours_category', y='Notas', marker='o', color='green')
plt.title('Média de Notas por Categoria de Horas de Estudo')
plt.xlabel('Horas de Estudo')
plt.ylabel('Média de Notas')
plt.grid(False) # Removido as linhas de grade
plt.xticks(rotation=0, ha='right')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Criar faixas de horas de uso
df['faixa_uso'] = pd.cut(
  df['Uso_de_Dispositivo'],
  bins=[0, 2, 4, 6, 9, 12],
  labels=['0-2h', '2-4h', '4-6h', '6-8h', '8h+']
)

# Mapear os níveis de estresse para valores numéricos
stress_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
df['stress_level_numeric'] = df['Nível_de_Estresse'].map(stress_mapping)

# Média do estresse por faixa - adicionando observed=True
dados = df.groupby('faixa_uso', observed=True)['stress_level_numeric'].mean()

plt.figure(figsize=(7,4))
dados.plot(kind='bar', color=['rosybrown', 'palevioletred', 'plum', 'mediumorchid', 'purple'])

plt.title('Horas de uso de dispositivos e nível de estresse')
plt.xlabel('Faixa de horas de uso')
plt.ylabel('Nível médio de estresse')
plt.xticks(rotation=0)

plt.show()

"""**OBRIGADA!**"""